### PR TITLE
Fix for over-frequent tick timer callbacks

### PR DESCRIPTION
**Pull request by lepinsk**
Right now the watchface subscribes to the tick timer at `SECOND_UNIT` granularity and leaves it at that. Given that (beyond the initial loading animation), the watchface is only updated every minute, this seems unnecessary. I'm not sure quite how much of a battery drain this is, but better to err on the side of caution, I suppose.

Anyway, all this does is unsubscribe from the second-timer once the loading animation has completed and changes it to a minute-timer.

The only possible caveat: when `request_weather()` is called after 15 minutes, the display won't be updated with the new weather data until the _next_ timer tick, 60s later. If this is a real concern, it'd be possible to set the timer back to 1s refreshing while the weather data is being loaded, but I figured this would introduce unnecessary extra logic (and an opportunity for me to bug something out)...

### CODE REVIEW

**Comment by Niknam** [comment]
Thanks for the effort, Julian! I'll merge it whenever I have some more time on my hands.

I don't know if you have noticed it as well, but sometimes the display flickers, as if all the elements were reloaded. Don't know if this has anything to do with that, but it will be interesting to find out. 

Thanks again!

**Comment by lepinsk** [comment]
Hmm, that's interesting – I don't know if I've noticed that happening, but I'll keep an eye out for it.

(Also, this isn't ready for primetime yet, but I've been working with @AkaokA on a watchface that we used a bunch of the Futura Weather innards on – [French for Future](https://github.com/lepinsk/french-for-future).)

**Comment by lepinsk** [comment]
Just realized that this means that failed weather requests take a whole bunch of time to resolve. I'd advise against merging – looking into it...

**Comment by Niknam** [comment]
That is actually a current issue (i.e. with the latest official release) that I've been trying to resolve. When testing one of my betas, I noticed that `request_weather` does not update the displayed weather info but merely gets updated info from the provider and then stores it until `weather_layer_set_icon` and `weather_layer_set_temperature` updates the display. 

Feel free to double check. I haven't figured out a good solution yet. Let me know if you have any ideas!

**Comment by lepinsk** [comment]
Interesting. I'll look into it. I'm also noticing that Futura Weather and our own fork are showing [different weather](https://github.com/lepinsk/french-for-future/issues/9) for the same place – not sure what's going on, so I'll poke around a bit.

_Also:_ In looking into the documentation on adding a configuration page, it looks like the `appinfo.json` is supposed to have a `capabilities` field with `location` as one of its keys. I don't know if the docs are out of date, but it doesn't look like Futura Weather has that set (but I can't seem to see if affecting anything...).

**Comment by Niknam** [comment]
Thanks! I appreciate every additional pair of eyes since I have a real hard time allocating time for this project at the moment.

Regarding the `capabilities` field, it is not required to have that field at all according to Table 1 on [this page](http://developer.getpebble.com/2/guides/anatomy-of-pebble-application.html). And although it seems valid to make use of the `location` capability, it is apparently not affecting anything as far as I can notice either.

**Comment by Niknam** [comment]
By the way, forget what I wrote about `request_weather` earlier. The problem was within the `updateWeather()` function in `pebble-js-app.js`. Upon an HTTP error, the watch was continuously looped into the `else` clause, and thus the error was never visibly resolved (although it was technically resolved in the background).

I "fixed" it by commenting out everything except the content of the `if` clause. It's included in [this beta](https://www.dropbox.com/s/55ai3foqrvq42q8/Futura_Weather_2-1_SDK2-beta20140321.pbw). The beta also features a better error handling, which more resembles the one in the 1.x versions. Try it out for a couple of days when you get the chance and let me know how it runs.

**Comment by lepinsk** [comment]
I'm going to go ahead and close this merge request; looks like [this pull](https://github.com/Niknam/futura-weather-sdk2.0/pull/8) supersedes this.

**Pull request closed without merging**
